env:
  es6: true
  node: true
extends: eslint:all
parser: babel-eslint
parserOptions:
  sourceType: module
rules:
  array-element-newline:
    - off
  complexity:
    - warn
    - 10
  func-style:
    - error
    - declaration
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  max-len:
    - error
    - 100
  max-statements:
    - error
    - 20
  no-console:
    - off
  no-empty-function:
    - off
  no-magic-numbers:
    - off
  no-process-exit:
    - off
  one-var:
    - error
    - never
  padded-blocks:
    - error
    - never
  quote-props:
    - error
    - consistent-as-needed
  quotes:
    - error
    - single
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - never
